// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/29/2025, 10:02:11 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["G:/99.Github/toolutils/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/toolutils/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/toolutils/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/toolutils/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/toolutils/plugins/**/*.{js,ts,mjs}","G:/99.Github/toolutils/composables/**/*.{js,ts,mjs}","G:/99.Github/toolutils/utils/**/*.{js,ts,mjs}","G:/99.Github/toolutils/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/toolutils/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/toolutils/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","G:/99.Github/toolutils/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;