// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/8/2025, 3:38:37 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/97.Github/MyRepository/toolutils/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/97.Github/MyRepository/toolutils/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/97.Github/MyRepository/toolutils/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/97.Github/MyRepository/toolutils/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/97.Github/MyRepository/toolutils/plugins/**/*.{js,ts,mjs}","E:/97.Github/MyRepository/toolutils/composables/**/*.{js,ts,mjs}","E:/97.Github/MyRepository/toolutils/utils/**/*.{js,ts,mjs}","E:/97.Github/MyRepository/toolutils/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/97.Github/MyRepository/toolutils/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/97.Github/MyRepository/toolutils/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/97.Github/MyRepository/toolutils/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;